### ISSUE TITLE
Not working at all in a subdomain...

### ISSUE THREAD

**Issue by damixhan** [Bit-Apps-Pro/bit-assist#4]
I buyed the app on AppSumo, it looks promising. I was testing it today but no luck... I setup a subdomain with wordpress just for testing plugins and BitAssist is not working at all.

I can create widgets, I think everything in the backend works but nothing showed up on front end (logged or private mode), with cached page or cache flushed.

My server is at SiteGround and this is the very first time having issues with a plugin. WP Version 6.1.1, Apache and Nginx, default wp theme and Astra too, just few other plugins activated like the BitIntegration (which can not connect to BitAssist form webhook neither)

I try to modify lot of times the Page Filter, delay in second, scroll % and no result at all...

I'm thinking that is due to SUBDOMAIN as your pre-refill the setting as domain and is not editable, so it doesn't grab the subdomain part; example: subdomain.domain.com becomes pre-refilled as domain.com in the Page Filter option.

Also I wonder if you leave the Page Filter blank it means is not showing anywhere or it means is showing everywhere?? I also tried to leave it blank as default but no luck.

Thank you for such amazing plugin and for your time and dedication.

**Comment by shuvomohajan** [comment]
Please, contact our support team at [support@bitapps.pro](mailto:support@bitapps.pro).

Note: All these issues you mentioned above are not related to this repository. This is an open-source SaaS version of the WordPress plugin.
